apiVersion: v1
kind: Pod
metadata:
  name: flume-ng
  labels:
    run: flume-ng
spec:
  containers:
    - args:
        - /bin/bash
      image: hishailesh77/flume
      imagePullPolicy: Always
      name: flume-ng
      resources:
        requests:
          cpu: 100m
      stdin: true
      terminationMessagePath: /dev/termination-log
      terminationMessagePolicy: File
  restartPolicy: Always
  schedulerName: default-scheduler
status:
  phase: Pending
  qosClass: Burstable
