apiVersion: v1
kind: Service
metadata:
  name: kafka-zookeeper
  labels:
    app: kafka-zookeeper
spec:
  ports:
    - port: 2181
  clusterIP: None
  selector:
    app: kafka-zookeeper
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: kafka-zookeeper
spec:
  selector:
    matchLabels:
      app: kafka-zookeeper
  serviceName: "kafka-zookeeper"
  replicas: 3
  podManagementPolicy: Parallel
  template:
    metadata:
      labels:
        app: kafka-zookeeper
    spec:
      containers:
        - name: kafka-zookeeper
          imagePullPolicy: Always
          image: "hishailesh77/kafka-zookeeper:latest"
          resources:
            requests:
              memory: "8Gi"
              cpu: "4"
          command: ["sh", "-c", "/app/kafka_zookeeper_setup.sh"]
          ports:
            - containerPort: 2181
          env:
            - name: KAFKA_DATADIR
              value: "/data/kafka"
          volumeMounts:
            - name: data
              mountPath: /data/kafka
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 80Gi
---

