apiVersion: v1
kind: Service
metadata:
  name: kafka-zookeeper
  labels:
    app: kafka-zookeeper
spec:
  ports:
    - port: 2181
  clusterIP: None
  selector:
    app: kafka-zookeeper
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: kafka-zookeeper
spec:
  selector:
    matchLabels:
      app: kafka-zookeeper
  serviceName: "kafka-zookeeper"
  replicas: 3
  podManagementPolicy: Parallel
  template:
    metadata:
      labels:
        app: kafka-zookeeper
    spec:
      containers:
        - name: shard
          imagePullPolicy: Always
          image: "hishailesh77/cassandra"
          command: ["sh", "-c", "tail -f /dev/null"]
          ports:
            - containerPort: 2181
          env:
            - name: MEHDB_DATADIR
              value: "/mehdbdata"
          volumeMounts:
            - name: data
              mountPath: /mehdbdata
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 1Gi
---
